# Generated by Django 2.2.4 on 2021-01-27 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Stores',
        ),
    ]
