# Generated by Django 2.2.4 on 2021-01-28 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_auto_20210127_2004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stores',
            new_name='Products',
        ),
    ]
