# Generated by Django 2.2.4 on 2021-01-29 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_auto_20210129_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='store',
            new_name='store_id',
        ),
    ]
