# Generated by Django 2.2.4 on 2021-01-29 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_auto_20210129_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='product_id',
        ),
        migrations.AddField(
            model_name='stock',
            name='product_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='stock_product', to='store_app.Product'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='stock',
            name='store_id',
        ),
        migrations.AddField(
            model_name='stock',
            name='store_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='stock_store', to='store_app.Store'),
            preserve_default=False,
        ),
    ]
