# Generated by Django 2.2.4 on 2021-01-29 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_auto_20210129_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='store_id',
            new_name='store',
        ),
    ]
